name: build
on: [pull_request, push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v4

      - name: install debootstrap
        run:  |
          git clone --depth=1 https://salsa.debian.org/installer-team/debootstrap/
          sudo chmod 0755 debootstrap/debootstrap
          sudo ln -s $(realpath debootstrap/debootstrap) -t /usr/bin
          sudo ln -s $(realpath debootstrap) -t /usr/share/
      - name: install qemu-user-static
        run:  sudo apt install qemu-user-static

      - name: bootstrap debian aarch64
        run: |
          sudo debootstrap --arch=arm64 sid /rootfs-build
          sudo mount --bind /proc /rootfs-build/proc
          sudo mount --bind /dev /rootfs-build/dev

      - name: install dependencies
        run: |
          sudo chroot /rootfs-build /bin/su -l root -c /bin/bash -c "apt-get update"
          sudo chroot /rootfs-build /bin/su -l root -c /bin/bash -c "apt-get install -y g++ cmake uuid-dev zlib1g-dev libssl-dev build-essential git"

      - name: copy source
        run: |
          sudo mkdir /rootfs-build/project
          sudo cp -r * /rootfs-build/project

      - name: build
        run: |
          sudo chroot /rootfs-build /bin/su -l root -c /bin/bash -c "cd /project && bash -e init_source.sh"
          sudo chroot /rootfs-build /bin/su -l root -c /bin/bash -c "cd /project && cmake -B build"
          sudo chroot /rootfs-build /bin/su -l root -c /bin/bash -c "cd /project && cmake --build build -j"

      - name: upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Artifacts
          path: /rootfs-build/project/build/dsu_updater